In [1]:
import sys
sys.path.append('./../../')

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

#Own Library modules
import src
# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

from src.feature_engineering import clean_functions as cf

In [2]:
#Corriendo el script que limpia los datos
datos_limpios = cf.prepara_datos()

	-> Importando los datos
	-> Limpiamos los nombres de las columnas
	-> Unimos los datasets
	-> Limpiamos los errores en los datos del cuestionario
	-> Limpiamos los datos de entidad sostenimiento y subsistema
	-> Agrupamos la variable de subsistema
	-> Creamos variables categóricas no binarias
	-> Convertimos las respuestas del cuestionario de string a numéricas

/Users/Karla_Alfaro_Pizana/Library/Python/3.7/lib/python/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

	-> Recodificamos variables categóricas binarias
	-> Imputamos las columnas con missings con la mediana
	-> Exportando un csv con los datos limpios

In [3]:
datos_limpios.head()

,nofolio,genero,ent,nom_ent,cct,modalidad,sost,subsist,hlec,nvl_esp,...,p70_E,p70_F,p70_G,p70_H,p74_A,p74_B,p74_C,p74_D,p74_E,p74_F
0,010000023B16,M,1,aguascalientes,01DBH0004I,bachillerato_general,federal,colbach/otros_federales,-0.76369,I,...,0,0,0,0,1,0,0,0,0,0
1,010000037B16,H,1,aguascalientes,01DBH0004I,bachillerato_general,federal,colbach/otros_federales,0.97389,III,...,0,0,0,0,1,0,0,0,0,0
2,010000008B16,M,1,aguascalientes,01DBH0004I,bachillerato_general,federal,colbach/otros_federales,0.26655,II,...,0,0,0,0,1,0,0,0,0,0
3,010000035B16,H,1,aguascalientes,01DBH0004I,bachillerato_general,federal,colbach/otros_federales,0.36393,II,...,0,0,0,0,1,0,0,0,0,0
4,010000032B16,H,1,aguascalientes,01DBH0004I,bachillerato_general,federal,colbach/otros_federales,0.97389,III,...,0,0,0,0,0,0,0,1,0,0

In [4]:
datos_limpios.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 560626 entries, 0 to 560625
Columns: 250 entries, nofolio to p74_F
dtypes: float64(157), int64(1), object(9), uint8(83)
memory usage: 783.0+ MB

In [5]:
#Corroborando que se agrupó bien la variable de subsistema
sorted(datos_limpios['subsist'].unique().tolist())

['bach_estatal_dge-cge',
 'bachillerato_autonomo',
 'cecyte',
 'cobach',
 'colbach/otros_federales',
 'conalep',
 'dgeti',
 'particulares/a.c.',
 'telebach/emsad']

In [6]:
#Corroborando que se crearon bien las variables categóricas no binarias
list(datos_limpios.columns)

['nofolio',
 'genero',
 'ent',
 'nom_ent',
 'cct',
 'modalidad',
 'sost',
 'subsist',
 'hlec',
 'nvl_esp',
 'hmat',
 'nvl_mat',
 'p1',
 'p2',
 'p3',
 'p4',
 'p5',
 'p6',
 'p7',
 'p8',
 'p9',
 'p10',
 'p11',
 'p12',
 'p13',
 'p14',
 'p15',
 'p16',
 'p17',
 'p18',
 'p19',
 'p20',
 'p21',
 'p22',
 'p23',
 'p24',
 'p25',
 'p26',
 'p27',
 'p28',
 'p29',
 'p30',
 'p31',
 'p32',
 'p33',
 'p34',
 'p35',
 'p36',
 'p37',
 'p38',
 'p39',
 'p40',
 'p41',
 'p42',
 'p43',
 'p44',
 'p45',
 'p46',
 'p47',
 'p48',
 'p49',
 'p50',
 'p51',
 'p52',
 'p53',
 'p54',
 'p55',
 'p56',
 'p57',
 'p58',
 'p59',
 'p60',
 'p61',
 'p62',
 'p63',
 'p64',
 'p65',
 'p66',
 'p67',
 'p68',
 'p69',
 'p70',
 'p71',
 'p72',
 'p73',
 'p74',
 'p75',
 'p76',
 'p77',
 'p78',
 'p79',
 'p80',
 'p81',
 'p82',
 'p83',
 'p84',
 'p85',
 'p86',
 'p87',
 'p88',
 'p89',
 'p90',
 'p91',
 'p92',
 'p93',
 'p94',
 'p95',
 'p96',
 'p97',
 'p98',
 'p99',
 'p100',
 'p101',
 'p102',
 'p103',
 'p104',
 'p105',
 'p106',
 'p107',
 'p108',
 'p109',
 'p110',
 'p111',
 'p112',
 'p113',
 'p114',
 'p115',
 'p116',
 'p117',
 'p118',
 'p119',
 'p120',
 'p121',
 'p122',
 'p123',
 'p124',
 'p125',
 'p126',
 'p127',
 'p128',
 'p129',
 'p130',
 'p131',
 'p132',
 'p133',
 'p134',
 'p135',
 'p136',
 'p137',
 'p138',
 'p139',
 'p140',
 'p141',
 'p142',
 'p143',
 'p144',
 'p145',
 'p146',
 'p147',
 'p148',
 'p149',
 'p150',
 'p151',
 'p152',
 'p153',
 'p154',
 'fac',
 'nom_ent_aguascalientes',
 'nom_ent_baja_california',
 'nom_ent_baja_california_sur',
 'nom_ent_campeche',
 'nom_ent_chiapas',
 'nom_ent_chihuahua',
 'nom_ent_coahuila',
 'nom_ent_colima',
 'nom_ent_distrito_federal',
 'nom_ent_durango',
 'nom_ent_estado_de_mexico',
 'nom_ent_guanajuato',
 'nom_ent_guerrero',
 'nom_ent_hidalgo',
 'nom_ent_jalisco',
 'nom_ent_michoacan',
 'nom_ent_morelos',
 'nom_ent_nayarit',
 'nom_ent_nuevo_leon',
 'nom_ent_oaxaca',
 'nom_ent_puebla',
 'nom_ent_queretaro',
 'nom_ent_quintana_roo',
 'nom_ent_san_luis_potosi',
 'nom_ent_sinaloa',
 'nom_ent_sonora',
 'nom_ent_tabasco',
 'nom_ent_tamaulipas',
 'nom_ent_tlaxcala',
 'nom_ent_veracruz',
 'nom_ent_yucatan',
 'nom_ent_zacatecas',
 'modalidad_bachillerato_general',
 'modalidad_bachillerato_tecnologico',
 'modalidad_tecnico_profesional',
 'sost_autonomas',
 'sost_estatal',
 'sost_federal',
 'sost_particulares',
 'subsist_bach_estatal_dge-cge',
 'subsist_bachillerato_autonomo',
 'subsist_cecyte',
 'subsist_cobach',
 'subsist_colbach/otros_federales',
 'subsist_conalep',
 'subsist_dgeti',
 'subsist_particulares/a.c.',
 'subsist_telebach/emsad',
 'p3_A',
 'p3_B',
 'p3_C',
 'p4_A',
 'p4_B',
 'p4_C',
 'p5_A',
 'p5_B',
 'p5_C',
 'p9_A',
 'p9_B',
 'p9_C',
 'p9_D',
 'p9_E',
 'p9_F',
 'p9_G',
 'p67_A',
 'p67_B',
 'p67_C',
 'p67_D',
 'p67_E',
 'p70_A',
 'p70_B',
 'p70_C',
 'p70_D',
 'p70_E',
 'p70_F',
 'p70_G',
 'p70_H',
 'p74_A',
 'p74_B',
 'p74_C',
 'p74_D',
 'p74_E',
 'p74_F']

In [7]:
#Corroborando que se recodificaron bien las variables categóricas binarias
sorted(datos_limpios['p69'].unique().tolist())

[0.0, 1.0]

In [8]:
#Corroborando que no hayan missgins en las categóricas no binarias
sorted(datos_limpios['p74_A'].unique().tolist())

[0, 1]

In [9]:
# Contador de valores nulos por cada columna
cf.cuenta_nulos_por_columnas(datos_limpios)

El dataframe tiene 250 columnas.
Hay 0 columnas que tienen NA's.

Empty DataFrame
Columns: [Missing Values, % del Total]
Index: []

In [10]:
# Contador de valores nulos por cada renglon
#cf.cuenta_nulos_por_renglones(datos_limpios)